name: crispr-rna-seq-env
channels:
  - conda-forge
  - bioconda
  - defaults
dependencies:
  - python=3.11
  - r-base=4.4
  - r-essentials
  - bioconductor-deseq2
  - bioconductor-edgeR
  - bioconductor-clusterprofiler
  - pandas
  - networkx
  - matplotlib
  - seaborn
  - pip:
      - biopython
